default: &default
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kember_development
test:
  <<: *default
  database: kember_test
production:
  <<: *default
  database: kember_production
  username: kember
  password: <%= ENV['KEMBER_DATABASE_PASSWORD'] %>